Fix for #1
l0rd/containerspatterns pull request #2
Opened 2018-02-13 06:52 UTC by danielleberre

The links to the examples are incomplete. This PR fixes the links to see the examples in github.io

2018-02-19 13:36 UTC, dolmen requested changes
Most "fixed" links aren't: 404 :(

2018-02-19 13:36 UTC, dolmen commented on snowcampio-2018-01-26.md
> +**Source code**<br>https://l0rd.github.io/containerspatterns/dfd
https://l0rd.github.io/containerspatterns/dfd => 404 :(

2018-02-19 13:36 UTC, dolmen commented on snowcampio-2018-01-26.md
> +**Source code**<br>https://l0rd.github.io/containerspatterns/OBI
https://l0rd.github.io/containerspatterns/OBI => 404 :(

2018-02-19 13:36 UTC, dolmen commented on snowcampio-2018-01-26.md
> +**Source code**<br>https://l0rd.github.io/containerspatterns/EFE/
https://l0rd.github.io/containerspatterns/EFE/ => 404 :(

2018-02-19 13:36 UTC, dolmen commented on snowcampio-2018-01-26.md
> +**Source code**<br>https://l0rd.github.io/containerspatterns/ECC
https://l0rd.github.io/containerspatterns/ECC => 404 :(

2018-02-19 13:36 UTC, dolmen commented on snowcampio-2018-01-26.md
> +**Source code**<br>https://l0rd.github.io/containerspatterns/DYT
https://l0rd.github.io/containerspatterns/DYT => 404 :(

2018-02-19 13:36 UTC, dolmen commented on snowcampio-2018-01-26.md
> +**Source code**<br>https://l0rd.github.io/containerspatterns/CL
The final URL is https://l0rd.github.io/containerspatterns/CL/

2018-02-19 13:36 UTC, dolmen commented on snowcampio-2018-01-26.md
> +**Source code**<br>https://l0rd.github.io/containerspatterns/HS
https://l0rd.github.io/containerspatterns/HS => 404 :(

2018-02-19 13:36 UTC, dolmen commented on snowcampio-2018-01-26.md
> +**Source code**<br>https://l0rd.github.io/containerspatterns/S2I
The final URL is https://l0rd.github.io/containerspatterns/S2I/

2018-02-19 13:36 UTC, dolmen commented on snowcampio-2018-01-26.md
> +**Source code**<br>https://l0rd.github.io/containerspatterns/SC
The final URL is https://l0rd.github.io/containerspatterns/SC/

2018-02-19 13:36 UTC, dolmen commented on snowcampio-2018-01-26.md
> +**Source code**<br>https://l0rd.github.io/containerspatterns/DSM
The final URL is https://l0rd.github.io/containerspatterns/DSM/

2018-02-19 13:36 UTC, dolmen commented on snowcampio-2018-01-26.md
> +**Source code**<br>https://l0rd.github.io/containerspatterns/DYT
https://l0rd.github.io/containerspatterns/DYT => 404 :(

2018-02-19 13:36 UTC, dolmen commented on snowcampio-2018-01-26.md
>  <br>https://github/polyfunc/flask-todolist
This link is incorrect too.

2018-02-19 19:16 UTC, danielleberre commented
@dolmen I used the full github.com links when the github.io link do not work.

Not sure the links are expected to be that way ...

2018-05-17 20:08 UTC, l0rd commented
Fixed, thanks for the PR

2018-05-17 20:08 UTC, closed without merging